stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

pytest:
  stage: test
  image: python:3.11
  before_script:
    - pip install .[dev]
  script:
    - pytest --cov=cierre_farmacias_app --cov-report=xml
    - bandit -r cierre_farmacias_app -ll --exit-zero
    - safety check --full-report || true
