version: '3.8'
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: development
    environment:
      - ENV=development
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: python run.py
    env_file:
      - .env.example
