version: '3.8'
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: production
    environment:
      - ENV=production
    ports:
      - "5000:5000"
    command: gunicorn run:app --bind 0.0.0.0:5000
    env_file:
      - .env.example
