openapi: 3.0.3
info:
  title: Cierre de Farmacias API
  version: 1.0.0
  description: API para gestionar cierres de farmacias.
servers:
  - url: http://localhost:5000
paths:
  /login:
    get:
      summary: Mostrar formulario de inicio de sesión
      responses:
        '200':
          description: Formulario HTML
    post:
      summary: Autenticar usuario
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '302':
          description: Redirige al dashboard en caso de éxito
        '401':
          description: Credenciales inválidas
  /logout:
    get:
      summary: Cerrar sesión del usuario
      responses:
        '302':
          description: Redirige al formulario de login
  /upload:
    get:
      summary: Formulario de carga de archivos
      responses:
        '200':
          description: Formulario HTML
    post:
      summary: Procesar carga de archivos Excel
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                tipo_general:
                  type: string
                  enum: [Baja, Traspaso]
              required:
                - file
                - tipo_general
      responses:
        '200':
          description: Resultado del procesamiento
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /data:
    get:
      summary: Obtener datos procesados
      responses:
        '200':
          description: Datos en formato JSON
          content:
            application/json: {}
  /summary:
    get:
      summary: Obtener resumen de datos
      responses:
        '200':
          description: Resumen en formato JSON
          content:
            application/json: {}
  /send_notifications:
    post:
      summary: Enviar notificaciones por correo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ceco:
                  type: string
                departamento:
                  type: string
              required:
                - ceco
                - departamento
      responses:
        '200':
          description: Resultado del envío
          content:
            application/json: {}
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
security:
  - cookieAuth: []
